### ISSUE TITLE
Error immediate closure

### ISSUE THREAD

**Issue by Maximus19777** [DockFrankenstein/SCPSL-voice#2]
every time i open the exe this error appears and the terminal closes
![error](https://user-images.githubusercontent.com/97364549/210831130-fd4468fb-2e74-405f-b4f1-93234ed461d7.PNG)

**Comment by ferafiks** [comment]
Voice Controller uses Window's Speech Recognition, so you'll have to install it. Go to Windows Settings/Time&Language/Speech and select your language

![image](https://user-images.githubusercontent.com/49789311/211139015-16dcb61a-af7d-4e3d-99dc-aa0987876d33.png)

**Comment by Maximus19777** [comment]
ok now it's working thanks
